default_job = "check"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.cli]
command = [
  "cargo", "run"
]

[jobs.compiler]
command = [
  "cargo", "test", "-p", "compiler", "tests"
]
need_stdout = true

[jobs.test]
command = [
  "cargo", "test", "-p", "lexer", "-p", "parser", "-p", "analyzer","--tests"
]
need_stdout = true

[jobs.install]
command = [
"cargo", "install", "--path", "."
]
