default_job = "check"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.test]
command = [
  "cargo", "test", "-p", "lexer", "-p", "parser", "-p", "analyzer", "--tests"
]
need_stdout = true
