[package]
name = "analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../common" }
diagnostics = { path = "../../diagnostics" }
syntax = { path = "../syntax" }
context = {path = "../context"}
parser = {path="../parser"}
lexer = {path="../lexer"}
